version: '3.8'

services:
  web:
    build: .
    ports:
      - "21213:21213"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=fileflicker
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - OPENAI_KEY=${OPENAI_KEY}
      - N8N_URL=${N8N_URL}
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: